spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    username: root
    password: felipe@123
    url: jdbc:mysql://localhost:3306/fornecedor
    driver-class-name: com.mysql.jdbc.Driver
    
